# Numpy Array

In [1]:
import numpy as np
np.array(["vbhvh", 2, 3]) # creating an simple array using np.array function

array(['vbhvh', '2', '3'], dtype='<U5')

In [2]:
type(np.array(["vbhvh", 2, 3])) # data type of a array created using numpy says ndarray means n-dimentional array

numpy.ndarray

In [3]:
#Upcasting:

In [4]:
np.array([1, 2, 3.0])    # numpy autometically convert all the elements inside an array to its higher data type

array([1., 2., 3.])

In [5]:
x=np.array([53,27,'anjali'])

In [6]:
type(np.array([53,27,'anjali']))

numpy.ndarray

In [7]:
#two dimensions

In [8]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.array([[26,94,32.5],['manu',64,42]])

array([['26', '94', '32.5'],
       ['manu', '64', '42']], dtype='<U32')

In [10]:
#Minimum dimensions 2:

In [11]:
np.array([1, 2, 3], ndmin=5) # we can manually set the number of dimention while dreatimg an array

array([[[[[1, 2, 3]]]]])

In [12]:
np.array(['abc',32.6,5],ndmin=10)

array([[[[[[[[[['abc', '32.6', '5']]]]]]]]]], dtype='<U4')

In [13]:
#dtype

In [14]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
#Data-type consisting of more than one element:

In [16]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [17]:
type(x[1][0])

numpy.int16

In [18]:
type(x[0][1])

numpy.int64

In [19]:

#Creating an array from sub-classes:

In [20]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [21]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [22]:
#Convert the input to an array.

In [23]:
#Convert a list into an array:

In [24]:
 a = [1, 2]
type(a)

list

In [25]:
type(np.asarray(a))

numpy.ndarray

In [26]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [27]:
np.asarray((1,2))

array([1, 2])

In [28]:
#If dtype is set, array is copied only if dtype does not match:

In [29]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [30]:
np.asarray([1,2]) is a

False

In [31]:
np.asarray([1,2])

array([1, 2])

In [32]:
np.asarray(a, dtype=np.float64) is a

False

In [33]:
# ndarray subclasses are not passed through

In [34]:
issubclass(np.matrix, np.ndarray)

True

In [35]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [36]:
np.asarray(a) is a

False

In [37]:
np.asanyarray(a) is a

True

In [38]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [39]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [40]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [41]:
np.asanyarray([1,2]) is a

False

In [42]:
np.array(a, copy=True)  

array([[1, 2]])

In [43]:
#Create an array x, with a reference y and a copy z:

In [48]:
x = np.array([1, 2, 3])
x


array([1, 2, 3])

In [49]:
y = x

In [50]:
z = np.copy(x)

In [51]:
y[0] = 100
x

array([100,   2,   3])

In [52]:
x

array([100,   2,   3])

In [53]:
id(x[0])

1664321669648

In [54]:
id(y[0])

1664321669680

In [55]:
id(x) 

1664322578672

In [56]:
id(y)

1664322578672

# numpy.fromfunction

In [57]:
#Construct an array by executing a function over each coordinate.

In [58]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [59]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [60]:
#Create a new 1-dimensional array from an iterable object.

In [61]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x00000183815D8270>

In [62]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [63]:
#A new 1-D array initialized from text data in a string

In [64]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [65]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [66]:
# How to create create a record array from a (flat) list of arrays

In [67]:
x1=np.array([1,2,3,4])

In [68]:
x2=np.array(['a','dd','xyz','12'])

In [69]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [70]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [71]:
print(r[1]["a"])

2


In [72]:
x1[1]

2

# data types

In [73]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [74]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [75]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [76]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [77]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [78]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [79]:
list(range(50,-1,5))

[]

In [80]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [81]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [82]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [83]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix creation

In [84]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [85]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [86]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [87]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [88]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [89]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [90]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [91]:
np.arange(3)

array([0, 1, 2])

In [92]:
np.arange(3.0)

array([0., 1., 2.])

In [93]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [94]:
np.arange(3,7,2)

array([3, 5])

In [95]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [96]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [97]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [98]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [99]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [100]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [101]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [102]:
#Extract a diagonal or construct a diagonal array.

In [103]:
x = np.arange(16).reshape((-1,4))

In [104]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
np.diag(x)

array([ 0,  5, 10, 15])

In [106]:
np.diag(x, k=2
       )

array([2, 7])

In [107]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [108]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [109]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [110]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [111]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [112]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [113]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [114]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [115]:
#return a Lower triangle of an array.

In [116]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [117]:
#return Upper triangle of an array.

In [118]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [ ]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

In [ ]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

In [ ]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


In [ ]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

# Reshaping

In [ ]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

In [ ]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


In [ ]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


In [ ]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


In [ ]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M

In [ ]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

In [ ]:
M

In [ ]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

# Indexing and slicing

In [ ]:
arr = np.arange(0,11)
print("Array:",arr)


In [ ]:
print("Element at 7th index is:", arr[7])


In [ ]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


In [ ]:
print("Elements up to 4th index are:", arr[:4])
arr

In [ ]:
print("Elements from last backwards are:", arr[-1:7:-1])


In [ ]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


In [ ]:
arr = np.arange(0,21,2)
print("New array:",arr)


In [ ]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

In [ ]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

In [ ]:
mat[0:3,[1,3]]
mat

In [ ]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat

In [ ]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")


In [ ]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


In [ ]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


In [ ]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

# Subseting

In [ ]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

In [ ]:
print ("Elements greater than 50\n", mat[mat>50])

# Slicing

In [ ]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


In [ ]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")

In [ ]:
mat_slice[0,0] = 1000
print (mat_slice)

In [ ]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


In [ ]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


In [ ]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)


In [ ]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)


In [ ]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)

# Universal Functions

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


In [ ]:
mat1*mat2

In [ ]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)


In [ ]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


In [ ]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


In [ ]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))

# Broadcasting

In [ ]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [ ]:
start = np.zeros((4,4))
start= start+100
start

In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

# Array Math

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


In [ ]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


In [ ]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


In [ ]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)

In [ ]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2

In [45]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [46]:
A = np.linspace(0,12*np.pi,1001)


In [47]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])