# Numpy- Numerical Python

In [1]:
import numpy as np

In [2]:
# numpy Array- Its homogeneous.
a=np.array([3,4,5])
a


array([3, 4, 5])

In [3]:
print(a)

[3 4 5]


In [4]:
print(a)
print('Dimension:',a.ndim) # gives dimension of array
print('Element Type:',a.dtype) #Data type

[3 4 5]
Dimension: 1
Element Type: int32


In [5]:
print('Shape:',a.shape)

Shape: (3,)


In [6]:
#create a 2-d array
a=np.array([[3,4,5],[7,8,6]])
a

array([[3, 4, 5],
       [7, 8, 6]])

In [7]:
print(a)

[[3 4 5]
 [7 8 6]]


In [8]:
print('shape:',a.shape)

shape: (2, 3)


In [9]:
print(a)
print('Dimension:',a.ndim)
print('Size:',a.size)
print('Element Type:', a.dtype)
print('shape:',a.shape)      

[[3 4 5]
 [7 8 6]]
Dimension: 2
Size: 6
Element Type: int32
shape: (2, 3)


In [10]:
# from above read from right side , 3(3,4,5)(7,8,6) elements in 1-d, 
# 2 elements in 2-d(both rows acts as 2-d)

# create an array of(2,3,2)


In [11]:
a=np.array([[2,3],[4,5],[6,7]])
print(a)

[[2 3]
 [4 5]
 [6 7]]


In [12]:
f=np.array([[[1,1],
           [2,2],
           [3,3]],
           
          [[4,4],
           [5,5],
           [6,6]]])

In [13]:
print(f)
print('Dimension:',f.ndim)
print('Size:',f.size)
print('Element Type:', f.dtype)
print('shape:',f.shape)   

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]
Dimension: 3
Size: 12
Element Type: int32
shape: (2, 3, 2)


# Arange

In [14]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
np.arange(24).reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
np.arange(25).reshape(5,5) # reshape product should be same as the arange number so that it exactly fits.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
np.arange(10,100,5).reshape(3,6) # (start,stop,step) 

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Linspace

In [22]:
np.linspace(10,100,5,dtype=int) # Linspace (start,stop, no.of elements instead of step)

array([ 10,  32,  55,  77, 100])

# Reshape


In [23]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
# Create 6-d data with arange having 6 elements in 1-d 
f= np.arange(6).reshape(1,1,1,1,1,6)

In [25]:
print(f)
print('Dimension:',f.ndim)
print('Size:',f.size)
print('Element Type:', f.dtype)
print('shape:',f.shape)  

[[[[[[0 1 2 3 4 5]]]]]]
Dimension: 6
Size: 6
Element Type: int32
shape: (1, 1, 1, 1, 1, 6)


# Ravel

In [26]:
f= f.ravel() # changes any dimension to 1-d
f

array([0, 1, 2, 3, 4, 5])

In [27]:
print('Dimension:',f.ndim)

Dimension: 1


In [28]:
a=np.array([[3,4,5],[7,8,6]])
a

array([[3, 4, 5],
       [7, 8, 6]])

In [29]:
a.ravel()

array([3, 4, 5, 7, 8, 6])

# Random Numbers

In [30]:
np.random.rand()

0.8946972006560923

In [31]:
np.random.rand()*100

76.24285417553266

In [32]:
int(np.random.rand()*100) #to remove an integer

81

In [33]:
np.random.rand(5)

array([0.6235505 , 0.13592425, 0.97728627, 0.23882325, 0.18720892])

In [34]:
np.random.randint(35,100) #random int btwn 35 to 100

49

In [35]:
#Create an array with random of 50, reshape it to 50,10 and take square root of it.

In [36]:
np.sqrt(np.random.randint(35,100,50).reshape(5,10))

array([[8.88819442, 8.1240384 , 6.70820393, 8.1240384 , 6.4807407 ,
        6.92820323, 7.61577311, 8.66025404, 9.79795897, 6.08276253],
       [7.93725393, 9.89949494, 8.36660027, 7.68114575, 6.        ,
        6.        , 7.81024968, 6.32455532, 7.93725393, 9.32737905],
       [9.74679434, 9.53939201, 6.08276253, 9.64365076, 7.68114575,
        7.54983444, 7.68114575, 7.87400787, 9.38083152, 9.2736185 ],
       [7.93725393, 7.14142843, 9.43398113, 9.64365076, 6.40312424,
        7.        , 8.30662386, 8.24621125, 8.88819442, 6.244998  ],
       [7.87400787, 6.63324958, 7.48331477, 9.74679434, 7.21110255,
        7.34846923, 8.48528137, 9.2736185 , 9.2736185 , 8.77496439]])

In [37]:
np.sqrt(np.random.rand(100))

array([0.28803587, 0.80229222, 0.99253808, 0.95371221, 0.70899835,
       0.39677516, 0.45091757, 0.5663151 , 0.99865681, 0.93756416,
       0.63955087, 0.90351519, 0.65396221, 0.97344096, 0.79973878,
       0.65227486, 0.58547338, 0.6305703 , 0.27421363, 0.17009002,
       0.36533957, 0.92245887, 0.55167229, 0.97972897, 0.99185259,
       0.87287311, 0.91232701, 0.83564081, 0.7117529 , 0.66743243,
       0.75087316, 0.57005274, 0.30513124, 0.34652462, 0.5089334 ,
       0.62141848, 0.55595527, 0.83349157, 0.92512402, 0.39669435,
       0.60059659, 0.60341158, 0.67523672, 0.34725721, 0.73478468,
       0.9934565 , 0.8831773 , 0.74422605, 0.68247745, 0.54730707,
       0.9504467 , 0.8116498 , 0.97281519, 0.98450468, 0.52249877,
       0.8349349 , 0.81242818, 0.46399373, 0.63352338, 0.83327857,
       0.62983624, 0.9549739 , 0.79674122, 0.68822697, 0.47215814,
       0.28815183, 0.8904423 , 0.9006816 , 0.068617  , 0.94813597,
       0.8001316 , 0.86840387, 0.84774054, 0.81469833, 0.61471

In [38]:
np.random.randint(30,100,50).reshape(10,5) # random nos from 30 to 100 and we need 50 nos of those

array([[73, 39, 75, 62, 83],
       [86, 32, 69, 96, 45],
       [65, 73, 43, 32, 30],
       [40, 63, 68, 43, 55],
       [45, 74, 97, 72, 65],
       [56, 69, 41, 34, 85],
       [52, 96, 65, 92, 54],
       [63, 47, 39, 88, 35],
       [41, 74, 38, 37, 37],
       [98, 93, 55, 69, 65]])

In [39]:
np.around(4.6) # rounf off to nearer number

5.0

np.sqrt(np.random.randint(40,100,20).reshape(4,5))

In [40]:
np.floor(4.2) # round off to lower value 

4.0

In [41]:
np.ceil(4.2) # rounf off to higher values

5.0

# Horizontal Split & Vertical Split

In [42]:
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [44]:
np.vsplit(a,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [45]:
np.hsplit(a,2)[0] # to obtain first part of array

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [46]:
np.hsplit(a,2)[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [47]:
np.vsplit(a,3)[2]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

# Horizontal Stack and Vertical Stack

In [48]:
a=np.arange(9).reshape(3,3)
b=np.arange(20,29).reshape(3,3)
print(a)
print('\n')
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [49]:
np.hstack((a,b))

array([[ 0,  1,  2, 20, 21, 22],
       [ 3,  4,  5, 23, 24, 25],
       [ 6,  7,  8, 26, 27, 28]])

In [50]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

# Add 2 integers to an array amd type cast it to float

In [51]:
a=np.array((2+5,6+3),dtype='float')
print(a)
print(a.dtype)

[7. 9.]
float64
